### ISSUE TITLE
Characterize storage efficiency

### ISSUE THREAD

**Issue by drewoldag** [LSSTDESC/qp_flexzboost#15]
Put together some information about storage size. Definitely required for reporting up the results of this work. Would be nice to include in the documentation as well.

**Comment by drewoldag** [comment]
A large portion of this has been taken care of, and is recorded in the documentation here: https://qp-flexzboost.readthedocs.io/en/latest/source/performance_comparison.html

**Comment by drewoldag** [comment]
It's possible that there's still some work to do to establish when it makes sense to use the qp_flexzboost approach vs when to use the qp.interp approach. i.e. for different numbers of basis_coefficients and different numbers of x grid values.

**Comment by drewoldag** [comment]
I've  done as much as I can at this point. The results are available in a couple of places.
Here in a google sheet: https://docs.google.com/spreadsheets/d/1UzpDHHQda8A7Oo1Qkl0gJjvCvAcuBqpuS11Gd3pL7p8/edit#gid=0

And here in the project journal: https://docs.google.com/document/d/1HGv0UuT0khlXtAUJF2IIPabs_Gsr77AOw-tG0rXI7y4/edit#heading=h.i6emxbpyj03

**Comment by eacharles** [comment]
Hmm.  I think there are a few other things we should be presenting, such as the time to evaluate the PDFs, and the accuracy we get if we convert arbitrary distributions into a particular format.

-e

**Comment by drewoldag** [comment]
Not sure if you had a chance to take a look at this page in the readthedocs: https://qp-flexzboost.readthedocs.io/en/latest/source/performance_comparison.html

I think that it covers some of what your asking for. I spent some time looking at run time and recorded the results there. 

I didn't look into specific accuracy for conversion of distribution formats though.

**Comment by aimalz** [comment]
> Hmm. I think there are a few other things we should be presenting, such as the time to evaluate the PDFs, and the accuracy we get if we convert arbitrary distributions into a particular format.

Just want to chime in to support the idea of a comprehensive comparison of storage parameterizations/number of parameters, like a souped up, modernized version of [the original qp paper](http://stacks.iop.org/1538-3881/156/i=1/a=35), but obviously not as part of this PR/issue.

**Comment by eacharles** [comment]
So, it think it is important to recognize that using the native representation of a PDF for a particular algorithm is going to generally look pretty close to losses, but in some sense that is because the algorithm already threw away the information that didn’t fit into the representation.   

I think it is also useful to see what happens when we try and force stuff into a particular parameterization from a different algorithm.     That helps us understand how generically we can use the different representations.

-e

**Comment by aimalz** [comment]
Re: information loss, yup, if the estimation algorithm entails imposing an insufficiently complex parameterization, no parameterization you save it as will recover complexities excluded by the estimation model itself. qp can only be used to optimize what we do once we have the output of an estimator we like. If the estimator makes choices that we think aren't going to accurately encapsulate the uncertainties, e.g. GPz when using only one Gaussian component, as in the DC1 experiment, then no way of saving it will meet the needs of consumers of the uncertainties.

Re: forcing a generic representation, exactly, that's the next step that was always planned as a follow-up to the original qp paper! We could easily define a DESC project on this that a student could complete in a summer.
